[devshell]
name = "flake-utils-plus"
packages = [
  "fd",
  "nixpkgs-fmt",
]

[[commands]]
name = "fmt"
help = "Check Nix formatting"
category = "checks"
command = "nixpkgs-fmt ${@} $DEVSHELL_ROOT"

[[commands]]
name = "evalnix"
help = "Check Nix parsing"
category = "checks"
command = "fd --extension nix --exec nix-instantiate --parse --quiet {} >/dev/null"

# Checks for fully featured example
[[commands]]
name = "nix-flake-check-ff"
help = "Run 'nix flake check'"
category = "checks (fully featured example)"
command = "cd $DEVSHELL_ROOT/examples/fully-featured && nix flake check ${@}"

[[commands]]
name = "nix-flake-show-ff"
help = "Run 'nix flake show'"
category = "checks (fully featured example)"
command = "cd $DEVSHELL_ROOT/examples/fully-featured && nix flake show ${@}"

[[commands]]
name = "nix-build-morty-ff"
help = "Build Morty configuration"
category = "checks (fully featured example)"
command = "cd $DEVSHELL_ROOT/examples/fully-featured && nix build .#nixosConfigurations.Morty.config.system.build.toplevel --dry-run"

[[commands]]
name = "nix-build-rick-ff"
help = "Build Rick configuration"
category = "checks (fully featured example)"
command = "cd $DEVSHELL_ROOT/examples/fully-featured && nix build .#someConfigurations.Rick.config.system.build.toplevel --dry-run"

# Checks for somewhat realistic example
[[commands]]
name = "nix-flake-check-sr"
help = "Run 'nix flake check'"
category = "checks (somewhat realistic example)"
command = "cd $DEVSHELL_ROOT/examples/somewhat-realistic && nix flake check ${@}"

[[commands]]
name = "nix-flake-show-sr"
help = "Run 'nix flake show'"
category = "checks (somewhat realistic example)"
command = "cd $DEVSHELL_ROOT/examples/somewhat-realistic && nix flake show ${@}"

[[commands]]
name = "nix-build-alice-sr"
help = "Build Alice configuration"
category = "checks (somewhat realistic example)"
command = "cd $DEVSHELL_ROOT/examples/somewhat-realistic && nix build .#nixosConfigurations.HostnameOne.config.system.build.toplevel --dry-run"

[[commands]]
name = "nix-build-carl-sr"
help = "Build Carl (darwin) configuration"
category = "checks (somewhat realistic example)"
command = "cd $DEVSHELL_ROOT/examples/somewhat-realistic && nix build .#darwinConfigurations.HostnameThree.config.system.build.toplevel --dry-run"


[[commands]]
name = "check-derivation-outputs"
help = "Checks derivation-outputs testcases"
category = "Tests"
command = "cd $DEVSHELL_ROOT/tests/derivation-outputs && nix flake show && nix flake check"

[[commands]]
name = "check-channel-patching"
help = "Checks channel-patching testcases"
category = "Tests"
command = "cd $DEVSHELL_ROOT/tests/channel-patching && nix flake show && nix flake check"

[[commands]]
name = "check-overlays-flow"
help = "Checks overlays-flow testcases"
category = "Tests"
command = "cd $DEVSHELL_ROOT/tests/overlays-flow && nix flake show && nix flake check"

[[commands]]
name = "check-hosts-config"
help = "Checks hosts-config testcases"
category = "Tests"
command = "cd $DEVSHELL_ROOT/tests/hosts-config && nix flake show && nix flake check"
